name: Notion Watcher

on:
  schedule:
    - cron: "0 4,10 * * *"   # 每天 UTC 04:00、10:00 → 台灣 12:00、18:00
  workflow_dispatch: {}


permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env from secrets
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
          echo "TELEGRAM_USER_ID=${{ secrets.TELEGRAM_USER_ID }}" >> .env
          echo "NOTION_URL=${{ secrets.NOTION_URL }}" >> .env

      - name: Show workspace & peek main.py
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          pwd
          ls -la
          echo "----- first 60 lines of ./main.py -----"
          sed -n '1,60p' ./main.py
          echo "----- search for 'Notion watcher is ready!' in repo -----"
          grep -Rni "Notion watcher is ready!" . || true

      - name: Run script
        run: python ./main.py
        working-directory: ${{ github.workspace }}

      - name: Commit last_hash if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_hash.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update last_hash [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
